services:
  # PostgreSQL for document metadata
  postgres:
    image: postgres:15-alpine
    container_name: knowledgehub-postgres
    environment:
      POSTGRES_DB: knowledgehub
      POSTGRES_USER: khuser
      POSTGRES_PASSWORD: khpassword
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/api/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "0.0.0.0:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U khuser -d knowledgehub"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - knowledgehub-network

  # Redis for caching and message queue
  redis:
    image: redis:7-alpine
    container_name: knowledgehub-redis
    command: >
      redis-server
      --appendonly yes
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
    volumes:
      - ./data/redis:/data
    ports:
      - "0.0.0.0:6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - knowledgehub-network

  # Weaviate vector database (without transformers for now)
  weaviate:
    image: semitechnologies/weaviate:1.22.4
    container_name: knowledgehub-weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'weaviate'
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    ports:
      - "0.0.0.0:8090:8080"
      - "0.0.0.0:50051:50051"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - knowledgehub-network

  # Transformer model for embeddings (commented out for now)
  # t2v-transformers:
  #   image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
  #   container_name: knowledgehub-transformers
  #   environment:
  #     ENABLE_CUDA: '0'
  #     MODEL_NAME: sentence-transformers/all-MiniLM-L6-v2
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G
  #   networks:
  #     - knowledgehub-network

  # MinIO for blob storage (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: knowledgehub-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
    ports:
      - "0.0.0.0:9010:9000"
      - "0.0.0.0:9011:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - knowledgehub-network

  # API Gateway
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: knowledgehub-api
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    environment:
      - APP_ENV=development
      - DEBUG=true
      - DATABASE_URL=postgresql://khuser:khpassword@postgres:5432/knowledgehub
      - REDIS_URL=redis://redis:6379/0
      - WEAVIATE_URL=http://knowledgehub-weaviate:8080
      - S3_ENDPOINT_URL=http://minio:9000
      - EMBEDDINGS_SERVICE_URL=http://embeddings-real:8100
      - ACTUAL_STORAGE_TB=11
    volumes:
      - ./src/api:/app/src/api
      - ./src/shared:/app/src/shared
      - ./src/web-ui:/app/src/web-ui:ro
      - /opt:/opt:ro
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      weaviate:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - knowledgehub-network
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 3000 --reload
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Server
  mcp-server:
    image: knowledgehub-mcp-server:fixed
    container_name: knowledgehub-mcp
    environment:
      - APP_ENV=development
      - API_URL=http://api:3000
      - MCP_SERVER_PORT=3002
    volumes:
      - ./src/mcp_server:/app/mcp_server
      - ./src/shared:/app/shared
    ports:
      - "0.0.0.0:3008:3002"
    depends_on:
      - api
    networks:
      - knowledgehub-network
    command: python -m mcp_server.start_with_health
    healthcheck:
      test: ["CMD", "/bin/bash", "/tmp/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Scraper Worker
  scraper:
    build:
      context: .
      dockerfile: docker/scraper.Dockerfile
    container_name: knowledgehub-scraper
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    environment:
      - APP_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://khuser:khpassword@postgres:5432/knowledgehub
      - API_URL=http://api:3000
      - API_KEY=dev-api-key-123
      - PYTHONPATH=/app
      - HEALTH_CHECK_PORT=3014
    volumes:
      - ./src:/app/src
    ports:
      - "0.0.0.0:3014:3014"
    depends_on:
      - redis
      - postgres
      - api
    networks:
      - knowledgehub-network
    command: ["sh", "-c", "cd /app && python -m src.scraper.main"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3014/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Scraper Worker 2 (for parallel crawling of different sources)
  scraper2:
    build:
      context: .
      dockerfile: docker/scraper.Dockerfile
    container_name: knowledgehub-scraper2
    environment:
      - APP_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://khuser:khpassword@postgres:5432/knowledgehub
      - API_URL=http://api:3000
      - API_KEY=dev-api-key-123
      - PYTHONPATH=/app
      - HEALTH_CHECK_PORT=3015
    volumes:
      - ./src:/app/src
    ports:
      - "0.0.0.0:3015:3015"
    depends_on:
      - redis
      - postgres
      - api
    networks:
      - knowledgehub-network
    command: ["sh", "-c", "cd /app && python -m src.scraper.main"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3015/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RAG Processor
  rag-processor:
    build:
      context: .
      dockerfile: docker/rag.Dockerfile
    container_name: knowledgehub-rag
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    environment:
      - APP_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://khuser:khpassword@postgres:5432/knowledgehub
      - WEAVIATE_URL=http://knowledgehub-weaviate:8080
      - API_URL=http://api:3000
      - API_KEY=dev-api-key-123
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - EMBEDDINGS_SERVICE_URL=http://host.docker.internal:8100
      - HEALTH_CHECK_PORT=3013
    volumes:
      - ./src/rag_processor:/app/src/rag_processor
      - ./src/shared:/app/src/shared
    ports:
      - "0.0.0.0:3013:3013"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - postgres
      - weaviate
      - api
    networks:
      - knowledgehub-network
    command: python -m src.rag_processor.main
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/bash", "/tmp/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web UI (development)
  web-ui:
    build:
      context: .
      dockerfile: docker/web-ui.Dockerfile
    container_name: knowledgehub-ui
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_WS_URL=ws://localhost:3000
    volumes:
      - ./src/web-ui:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:3102:80"
    depends_on:
      - api
    networks:
      - knowledgehub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Scheduler Service
  scheduler:
    build:
      context: .
      dockerfile: src/scheduler/Dockerfile
    container_name: knowledgehub-scheduler
    environment:
      - API_BASE_URL=http://api:3000
      - SCHEDULER_ENABLED=true
      - REFRESH_SCHEDULE=0 2 * * 0  # Every Sunday at 2 AM
      - REFRESH_BATCH_SIZE=2
      - REFRESH_DELAY_SECONDS=300
      - REFRESH_ON_STARTUP=false
    volumes:
      - ./src/scheduler:/app
      - ./src/shared:/app/shared
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - api
    networks:
      - knowledgehub-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  knowledgehub-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  weaviate_data:
  minio_data: