version: '3.8'

services:
  # Only test essential services for CI
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: khuser
      POSTGRES_PASSWORD: khpassword
      POSTGRES_DB: knowledgehub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U khuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
      args:
        REQUIREMENTS_FILE: requirements-ci.txt
    environment:
      DATABASE_URL: postgresql://khuser:khpassword@postgres:5432/knowledgehub
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: test
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5